--------------------------------------------------------
--  DDL for Package PKG_IUD
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PKG_IUD" 
IS 
PROCEDURE p_acrec_detail_iud                      (p_tip   VARCHAR2, p_row IN ACREC_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_acrec_detail_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ACREC_DETAIL);
PROCEDURE p_acrec_header_iud                      (p_tip   VARCHAR2, p_row IN ACREC_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_acrec_header_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ACREC_HEADER);
PROCEDURE p_ac_account_iud                        (p_tip   VARCHAR2, p_row IN AC_ACCOUNT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_ac_account_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_AC_ACCOUNT);
PROCEDURE p_ac_detail_iud                         (p_tip   VARCHAR2, p_row IN AC_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_ac_detail_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_AC_DETAIL);
PROCEDURE p_ac_document_iud                       (p_tip   VARCHAR2, p_row IN AC_DOCUMENT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_ac_document_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_AC_DOCUMENT);
PROCEDURE p_ac_header_iud                         (p_tip   VARCHAR2, p_row IN AC_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_ac_header_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_AC_HEADER);
PROCEDURE p_ac_period_iud                         (p_tip   VARCHAR2, p_row IN AC_PERIOD%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_ac_period_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_AC_PERIOD);
PROCEDURE p_app_audit_iud                         (p_tip   VARCHAR2, p_row IN APP_AUDIT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_audit_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_AUDIT);
PROCEDURE p_app_doc_number_iud                    (p_tip   VARCHAR2, p_row IN APP_DOC_NUMBER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_doc_number_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_DOC_NUMBER);
PROCEDURE p_app_securitem_iud                     (p_tip   VARCHAR2, p_row IN APP_SECURITEM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_securitem_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_SECURITEM);
PROCEDURE p_app_task_iud                          (p_tip   VARCHAR2, p_row IN APP_TASK%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_task_miud                         (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_TASK);
PROCEDURE p_app_task_param_iud                    (p_tip   VARCHAR2, p_row IN APP_TASK_PARAM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_task_param_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_TASK_PARAM);
PROCEDURE p_app_task_step_iud                     (p_tip   VARCHAR2, p_row IN APP_TASK_STEP%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_task_step_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_TASK_STEP);
PROCEDURE p_app_user_iud                          (p_tip   VARCHAR2, p_row IN APP_USER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_user_miud                         (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_USER);
PROCEDURE p_app_user_grant_iud                    (p_tip   VARCHAR2, p_row IN APP_USER_GRANT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_app_user_grant_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_APP_USER_GRANT);
PROCEDURE p_bom_group_iud                         (p_tip   VARCHAR2, p_row IN BOM_GROUP%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_bom_group_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_BOM_GROUP);
PROCEDURE p_bom_std_iud                           (p_tip   VARCHAR2, p_row IN BOM_STD%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_bom_std_miud                          (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_BOM_STD);
PROCEDURE p_bom_wo_iud                            (p_tip   VARCHAR2, p_row IN BOM_WO%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_bom_wo_miud                           (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_BOM_WO);
PROCEDURE p_calendar_iud                          (p_tip   VARCHAR2, p_row IN CALENDAR%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_calendar_miud                         (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_CALENDAR);
PROCEDURE p_cat_custom_iud                        (p_tip   VARCHAR2, p_row IN CAT_CUSTOM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_cat_custom_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_CAT_CUSTOM);
PROCEDURE p_cat_mat_type_iud                      (p_tip   VARCHAR2, p_row IN CAT_MAT_TYPE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_cat_mat_type_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_CAT_MAT_TYPE);
PROCEDURE p_colour_iud                            (p_tip   VARCHAR2, p_row IN COLOUR%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_colour_miud                           (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_COLOUR);
PROCEDURE p_costcenter_iud                        (p_tip   VARCHAR2, p_row IN COSTCENTER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_costcenter_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_COSTCENTER);
PROCEDURE p_cost_detail_iud                       (p_tip   VARCHAR2, p_row IN COST_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_cost_detail_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_COST_DETAIL);
PROCEDURE p_cost_header_iud                       (p_tip   VARCHAR2, p_row IN COST_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_cost_header_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_COST_HEADER);
PROCEDURE p_cost_type_iud                         (p_tip   VARCHAR2, p_row IN COST_TYPE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_cost_type_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_COST_TYPE);
PROCEDURE p_country_iud                           (p_tip   VARCHAR2, p_row IN COUNTRY%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_country_miud                          (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_COUNTRY);
PROCEDURE p_currency_iud                          (p_tip   VARCHAR2, p_row IN CURRENCY%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_currency_miud                         (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_CURRENCY);
PROCEDURE p_currency_rate_iud                     (p_tip   VARCHAR2, p_row IN CURRENCY_RATE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_currency_rate_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_CURRENCY_RATE);
PROCEDURE p_custom_iud                            (p_tip   VARCHAR2, p_row IN CUSTOM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_custom_miud                           (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_CUSTOM);
PROCEDURE p_delivery_condition_iud                (p_tip   VARCHAR2, p_row IN DELIVERY_CONDITION%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_delivery_condition_miud               (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_DELIVERY_CONDITION);
PROCEDURE p_efficiency_iud                        (p_tip   VARCHAR2, p_row IN EFFICIENCY%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_efficiency_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_EFFICIENCY);
PROCEDURE p_fa_trn_iud                            (p_tip   VARCHAR2, p_row IN FA_TRN%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_fa_trn_miud                           (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_FA_TRN);
PROCEDURE p_fa_trn_type_iud                       (p_tip   VARCHAR2, p_row IN FA_TRN_TYPE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_fa_trn_type_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_FA_TRN_TYPE);
PROCEDURE p_fifo_exceding_iud                     (p_tip   VARCHAR2, p_row IN FIFO_EXCEDING%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_fifo_exceding_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_FIFO_EXCEDING);
PROCEDURE p_fifo_material_iud                     (p_tip   VARCHAR2, p_row IN FIFO_MATERIAL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_fifo_material_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_FIFO_MATERIAL);
PROCEDURE p_fixed_asset_iud                       (p_tip   VARCHAR2, p_row IN FIXED_ASSET%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_fixed_asset_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_FIXED_ASSET);
PROCEDURE p_fixed_asset_categ_iud                 (p_tip   VARCHAR2, p_row IN FIXED_ASSET_CATEG%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_fixed_asset_categ_miud                (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_FIXED_ASSET_CATEG);
PROCEDURE p_group_routing_iud                     (p_tip   VARCHAR2, p_row IN GROUP_ROUTING%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_group_routing_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_GROUP_ROUTING);
PROCEDURE p_import_text_file_iud                  (p_tip   VARCHAR2, p_row IN IMPORT_TEXT_FILE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_import_text_file_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_IMPORT_TEXT_FILE);
PROCEDURE p_inventory_iud                         (p_tip   VARCHAR2, p_row IN INVENTORY%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_inventory_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_INVENTORY);
PROCEDURE p_inventory_detail_iud                  (p_tip   VARCHAR2, p_row IN INVENTORY_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_inventory_detail_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_INVENTORY_DETAIL);
PROCEDURE p_inventory_setup_iud                   (p_tip   VARCHAR2, p_row IN INVENTORY_SETUP%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_inventory_setup_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_INVENTORY_SETUP);
PROCEDURE p_inventory_stoc_iud                    (p_tip   VARCHAR2, p_row IN INVENTORY_STOC%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_inventory_stoc_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_INVENTORY_STOC);
PROCEDURE p_item_iud                              (p_tip   VARCHAR2, p_row IN ITEM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_item_miud                             (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ITEM);
PROCEDURE p_item_cost_iud                         (p_tip   VARCHAR2, p_row IN ITEM_COST%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_item_cost_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ITEM_COST);
PROCEDURE p_item_cycle_time_iud                   (p_tip   VARCHAR2, p_row IN ITEM_CYCLE_TIME%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_item_cycle_time_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ITEM_CYCLE_TIME);
PROCEDURE p_item_mapping_iud                      (p_tip   VARCHAR2, p_row IN ITEM_MAPPING%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_item_mapping_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ITEM_MAPPING);
PROCEDURE p_item_size_iud                         (p_tip   VARCHAR2, p_row IN ITEM_SIZE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_item_size_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ITEM_SIZE);
PROCEDURE p_item_type_iud                         (p_tip   VARCHAR2, p_row IN ITEM_TYPE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_item_type_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ITEM_TYPE);
PROCEDURE p_item_variable_iud                     (p_tip   VARCHAR2, p_row IN ITEM_VARIABLE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_item_variable_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ITEM_VARIABLE);
PROCEDURE p_line_iud                              (p_tip   VARCHAR2, p_row IN LINE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_line_miud                             (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_LINE);
PROCEDURE p_macrorouting_detail_iud               (p_tip   VARCHAR2, p_row IN MACROROUTING_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_macrorouting_detail_miud              (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_MACROROUTING_DETAIL);
PROCEDURE p_macrorouting_header_iud               (p_tip   VARCHAR2, p_row IN MACROROUTING_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_macrorouting_header_miud              (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_MACROROUTING_HEADER);
PROCEDURE p_movement_type_iud                     (p_tip   VARCHAR2, p_row IN MOVEMENT_TYPE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_movement_type_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_MOVEMENT_TYPE);
PROCEDURE p_multi_table_iud                       (p_tip   VARCHAR2, p_row IN MULTI_TABLE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_multi_table_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_MULTI_TABLE);
PROCEDURE p_operation_iud                         (p_tip   VARCHAR2, p_row IN OPERATION%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_operation_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_OPERATION);
PROCEDURE p_organization_iud                      (p_tip   VARCHAR2, p_row IN ORGANIZATION%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_organization_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ORGANIZATION);
PROCEDURE p_organization_loc_iud                  (p_tip   VARCHAR2, p_row IN ORGANIZATION_LOC%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_organization_loc_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_ORGANIZATION_LOC);
PROCEDURE p_package_detail_iud                    (p_tip   VARCHAR2, p_row IN PACKAGE_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_package_detail_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PACKAGE_DETAIL);
PROCEDURE p_package_header_iud                    (p_tip   VARCHAR2, p_row IN PACKAGE_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_package_header_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PACKAGE_HEADER);
PROCEDURE p_package_trn_detail_iud                (p_tip   VARCHAR2, p_row IN PACKAGE_TRN_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_package_trn_detail_miud               (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PACKAGE_TRN_DETAIL);
PROCEDURE p_package_trn_header_iud                (p_tip   VARCHAR2, p_row IN PACKAGE_TRN_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_package_trn_header_miud               (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PACKAGE_TRN_HEADER);
PROCEDURE p_parameter_iud                         (p_tip   VARCHAR2, p_row IN PARAMETER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_parameter_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PARAMETER);
PROCEDURE p_parameter_attr_iud                    (p_tip   VARCHAR2, p_row IN PARAMETER_ATTR%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_parameter_attr_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PARAMETER_ATTR);
PROCEDURE p_parameter_code_iud                    (p_tip   VARCHAR2, p_row IN PARAMETER_CODE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_parameter_code_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PARAMETER_CODE);
PROCEDURE p_patch_detail_iud                      (p_tip   VARCHAR2, p_row IN PATCH_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_patch_detail_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PATCH_DETAIL);
PROCEDURE p_patch_header_iud                      (p_tip   VARCHAR2, p_row IN PATCH_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_patch_header_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PATCH_HEADER);
PROCEDURE p_po_ord_header_iud                     (p_tip   VARCHAR2, p_row IN PO_ORD_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_po_ord_header_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PO_ORD_HEADER);
PROCEDURE p_po_ord_line_iud                       (p_tip   VARCHAR2, p_row IN PO_ORD_LINE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_po_ord_line_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PO_ORD_LINE);
PROCEDURE p_price_list_iud                        (p_tip   VARCHAR2, p_row IN PRICE_LIST%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_price_list_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PRICE_LIST);
PROCEDURE p_price_list_sales_iud                  (p_tip   VARCHAR2, p_row IN PRICE_LIST_SALES%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_price_list_sales_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PRICE_LIST_SALES);
PROCEDURE p_primary_uom_iud                       (p_tip   VARCHAR2, p_row IN PRIMARY_UOM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_primary_uom_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_PRIMARY_UOM);
PROCEDURE p_receipt_detail_iud                    (p_tip   VARCHAR2, p_row IN RECEIPT_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_receipt_detail_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_RECEIPT_DETAIL);
PROCEDURE p_receipt_header_iud                    (p_tip   VARCHAR2, p_row IN RECEIPT_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_receipt_header_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_RECEIPT_HEADER);
PROCEDURE p_reports_iud                           (p_tip   VARCHAR2, p_row IN REPORTS%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_reports_miud                          (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_REPORTS);
PROCEDURE p_reports_category_iud                  (p_tip   VARCHAR2, p_row IN REPORTS_CATEGORY%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_reports_category_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_REPORTS_CATEGORY);
PROCEDURE p_reports_parameter_iud                 (p_tip   VARCHAR2, p_row IN REPORTS_PARAMETER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_reports_parameter_miud                (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_REPORTS_PARAMETER);
PROCEDURE p_report_queue_detail_iud               (p_tip   VARCHAR2, p_row IN REPORT_QUEUE_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_report_queue_detail_miud              (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_REPORT_QUEUE_DETAIL);
PROCEDURE p_report_queue_header_iud               (p_tip   VARCHAR2, p_row IN REPORT_QUEUE_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_report_queue_header_miud              (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_REPORT_QUEUE_HEADER);
PROCEDURE p_sales_family_iud                      (p_tip   VARCHAR2, p_row IN SALES_FAMILY%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_sales_family_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SALES_FAMILY);
PROCEDURE p_sales_order_iud                       (p_tip   VARCHAR2, p_row IN SALES_ORDER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_sales_order_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SALES_ORDER);
PROCEDURE p_scan_event_iud                        (p_tip   VARCHAR2, p_row IN SCAN_EVENT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_scan_event_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SCAN_EVENT);
PROCEDURE p_setup_acrec_iud                       (p_tip   VARCHAR2, p_row IN SETUP_ACREC%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_setup_acrec_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SETUP_ACREC);
PROCEDURE p_setup_movement_iud                    (p_tip   VARCHAR2, p_row IN SETUP_MOVEMENT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_setup_movement_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SETUP_MOVEMENT);
PROCEDURE p_setup_receipt_iud                     (p_tip   VARCHAR2, p_row IN SETUP_RECEIPT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_setup_receipt_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SETUP_RECEIPT);
PROCEDURE p_setup_shipment_iud                    (p_tip   VARCHAR2, p_row IN SETUP_SHIPMENT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_setup_shipment_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SETUP_SHIPMENT);
PROCEDURE p_shipment_detail_iud                   (p_tip   VARCHAR2, p_row IN SHIPMENT_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_shipment_detail_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SHIPMENT_DETAIL);
PROCEDURE p_shipment_header_iud                   (p_tip   VARCHAR2, p_row IN SHIPMENT_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_shipment_header_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SHIPMENT_HEADER);
PROCEDURE p_shipment_order_iud                    (p_tip   VARCHAR2, p_row IN SHIPMENT_ORDER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_shipment_order_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SHIPMENT_ORDER);
PROCEDURE p_shipment_package_iud                  (p_tip   VARCHAR2, p_row IN SHIPMENT_PACKAGE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_shipment_package_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SHIPMENT_PACKAGE);
PROCEDURE p_so_detail_iud                         (p_tip   VARCHAR2, p_row IN SO_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_so_detail_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_SO_DETAIL);
PROCEDURE p_status_history_iud                    (p_tip   VARCHAR2, p_row IN STATUS_HISTORY%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_status_history_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STATUS_HISTORY);
PROCEDURE p_stg_bom_std_iud                       (p_tip   VARCHAR2, p_row IN STG_BOM_STD%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_bom_std_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_BOM_STD);
PROCEDURE p_stg_file_manager_iud                  (p_tip   VARCHAR2, p_row IN STG_FILE_MANAGER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_file_manager_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_FILE_MANAGER);
PROCEDURE p_stg_item_iud                          (p_tip   VARCHAR2, p_row IN STG_ITEM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_item_miud                         (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_ITEM);
PROCEDURE p_stg_parser_iud                        (p_tip   VARCHAR2, p_row IN STG_PARSER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_parser_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_PARSER);
PROCEDURE p_stg_receipt_iud                       (p_tip   VARCHAR2, p_row IN STG_RECEIPT%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_receipt_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_RECEIPT);
PROCEDURE p_stg_ship_fifo_iud                     (p_tip   VARCHAR2, p_row IN STG_SHIP_FIFO%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_ship_fifo_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_SHIP_FIFO);
PROCEDURE p_stg_work_order_iud                    (p_tip   VARCHAR2, p_row IN STG_WORK_ORDER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_work_order_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_WORK_ORDER);
PROCEDURE p_stg_wo_decl_iud                       (p_tip   VARCHAR2, p_row IN STG_WO_DECL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_stg_wo_decl_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_STG_WO_DECL);
PROCEDURE p_teh_variable_iud                      (p_tip   VARCHAR2, p_row IN TEH_VARIABLE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_teh_variable_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_TEH_VARIABLE);
PROCEDURE p_trn_plan_detail_iud                   (p_tip   VARCHAR2, p_row IN TRN_PLAN_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_trn_plan_detail_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_TRN_PLAN_DETAIL);
PROCEDURE p_trn_plan_header_iud                   (p_tip   VARCHAR2, p_row IN TRN_PLAN_HEADER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_trn_plan_header_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_TRN_PLAN_HEADER);
PROCEDURE p_value_ad_tax_iud                      (p_tip   VARCHAR2, p_row IN VALUE_AD_TAX%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_value_ad_tax_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VALUE_AD_TAX);
PROCEDURE p_virtual_table_iud                     (p_tip   VARCHAR2, p_row IN VIRTUAL_TABLE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_virtual_table_miud                    (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VIRTUAL_TABLE);
PROCEDURE p_vw_blo_grp_assoc_chk_miud             (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_BLO_GRP_ASSOC_CHK);
PROCEDURE p_vw_blo_import_wo_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_BLO_IMPORT_WO);
PROCEDURE p_vw_blo_prepare_trn_miud               (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_BLO_PREPARE_TRN);
PROCEDURE p_vw_blo_work_group_miud                (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_BLO_WORK_GROUP);
PROCEDURE p_vw_blo_work_order_miud                (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_BLO_WORK_ORDER);
PROCEDURE p_vw_excel_operations_miud              (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_EXCEL_OPERATIONS);
PROCEDURE p_vw_prep_pick_plan_iud                 (p_tip   VARCHAR2, p_row IN VW_PREP_PICK_PLAN%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_vw_prep_pick_plan_miud                (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_PREP_PICK_PLAN);
PROCEDURE p_vw_rep_bom_std_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_BOM_STD);
PROCEDURE p_vw_rep_deliv_miud                     (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_DELIV);
PROCEDURE p_vw_rep_fa_sheet_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_FA_SHEET);
PROCEDURE p_vw_rep_fifo_reg_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_FIFO_REG);
PROCEDURE p_vw_rep_grp_sheet_miud                 (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_GRP_SHEET);
PROCEDURE p_vw_rep_inv_list_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_INV_LIST);
PROCEDURE p_vw_rep_pkg_sit_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_PKG_SIT);
PROCEDURE p_vw_rep_po_order_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_PO_ORDER);
PROCEDURE p_vw_rep_wip_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_WIP);
PROCEDURE p_vw_rep_wip_grouped_miud               (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_REP_WIP_GROUPED);
PROCEDURE p_vw_wiz_miud                           (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_VW_WIZ);
PROCEDURE p_warehouse_iud                         (p_tip   VARCHAR2, p_row IN WAREHOUSE%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_warehouse_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WAREHOUSE);
PROCEDURE p_warehouse_categ_iud                   (p_tip   VARCHAR2, p_row IN WAREHOUSE_CATEG%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_warehouse_categ_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WAREHOUSE_CATEG);
PROCEDURE p_web_grid_cm_iud                       (p_tip   VARCHAR2, p_row IN WEB_GRID_CM%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_web_grid_cm_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WEB_GRID_CM);
PROCEDURE p_whs_trn_iud                           (p_tip   VARCHAR2, p_row IN WHS_TRN%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_whs_trn_miud                          (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WHS_TRN);
PROCEDURE p_whs_trn_detail_iud                    (p_tip   VARCHAR2, p_row IN WHS_TRN_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_whs_trn_detail_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WHS_TRN_DETAIL);
PROCEDURE p_whs_trn_reason_iud                    (p_tip   VARCHAR2, p_row IN WHS_TRN_REASON%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_whs_trn_reason_miud                   (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WHS_TRN_REASON);
PROCEDURE p_wiz_control_iud                       (p_tip   VARCHAR2, p_row IN WIZ_CONTROL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_wiz_control_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WIZ_CONTROL);
PROCEDURE p_workcenter_iud                        (p_tip   VARCHAR2, p_row IN WORKCENTER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_workcenter_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WORKCENTER);
PROCEDURE p_workcenter_oper_iud                   (p_tip   VARCHAR2, p_row IN WORKCENTER_OPER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_workcenter_oper_miud                  (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WORKCENTER_OPER);
PROCEDURE p_work_group_iud                        (p_tip   VARCHAR2, p_row IN WORK_GROUP%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_work_group_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WORK_GROUP);
PROCEDURE p_work_order_iud                        (p_tip   VARCHAR2, p_row IN WORK_ORDER%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_work_order_miud                       (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WORK_ORDER);
PROCEDURE p_work_season_iud                       (p_tip   VARCHAR2, p_row IN WORK_SEASON%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_work_season_miud                      (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WORK_SEASON);
PROCEDURE p_wo_detail_iud                         (p_tip   VARCHAR2, p_row IN WO_DETAIL%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_wo_detail_miud                        (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WO_DETAIL);
PROCEDURE p_wo_group_iud                          (p_tip   VARCHAR2, p_row IN WO_GROUP%ROWTYPE,p_set_line_id BOOLEAN default TRUE);
PROCEDURE p_wo_group_miud                         (p_tip   VARCHAR2, p_it_row IN OUT  NOCOPY PKG_RTYPE.ta_WO_GROUP);
END; 

/

/
