--------------------------------------------------------
--  DDL for Package PKG_GET2
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PKG_GET2" 
IS 
FUNCTION f_get_acrec_header_2                     (p_row IN OUT ACREC_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_acrec_header_2                    (p_row IN OUT ACREC_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_ac_account_2                       (p_row IN OUT AC_ACCOUNT%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_ac_account_2                      (p_row IN OUT AC_ACCOUNT%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_ac_document_2                      (p_row IN OUT AC_DOCUMENT%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_ac_document_2                     (p_row IN OUT AC_DOCUMENT%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_ac_header_2                        (p_row IN OUT AC_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_ac_header_2                       (p_row IN OUT AC_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_ac_period_2                        (p_row IN OUT AC_PERIOD%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_ac_period_2                       (p_row IN OUT AC_PERIOD%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_app_doc_number_2                   (p_row IN OUT APP_DOC_NUMBER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_app_doc_number_2                  (p_row IN OUT APP_DOC_NUMBER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_app_securitem_2                    (p_row IN OUT APP_SECURITEM%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_app_securitem_2                   (p_row IN OUT APP_SECURITEM%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_app_user_2                         (p_row IN OUT APP_USER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_app_user_2                        (p_row IN OUT APP_USER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_app_user_grant_2                   (p_row IN OUT APP_USER_GRANT%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_app_user_grant_2                  (p_row IN OUT APP_USER_GRANT%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_bom_std_2                          (p_row IN OUT BOM_STD%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_bom_std_2                         (p_row IN OUT BOM_STD%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_calendar_2                         (p_row IN OUT CALENDAR%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_calendar_2                        (p_row IN OUT CALENDAR%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_cat_mat_type_2                     (p_row IN OUT CAT_MAT_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_cat_mat_type_2                    (p_row IN OUT CAT_MAT_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_colour_2                           (p_row IN OUT COLOUR%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_colour_2                          (p_row IN OUT COLOUR%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_costcenter_2                       (p_row IN OUT COSTCENTER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_costcenter_2                      (p_row IN OUT COSTCENTER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_cost_type_2                        (p_row IN OUT COST_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_cost_type_2                       (p_row IN OUT COST_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_country_2                          (p_row IN OUT COUNTRY%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_country_2                         (p_row IN OUT COUNTRY%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_currency_2                         (p_row IN OUT CURRENCY%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_currency_2                        (p_row IN OUT CURRENCY%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_currency_rate_2                    (p_row IN OUT CURRENCY_RATE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_currency_rate_2                   (p_row IN OUT CURRENCY_RATE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_custom_2                           (p_row IN OUT CUSTOM%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_custom_2                          (p_row IN OUT CUSTOM%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_delivery_condition_2               (p_row IN OUT DELIVERY_CONDITION%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_delivery_condition_2              (p_row IN OUT DELIVERY_CONDITION%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_fa_trn_type_2                      (p_row IN OUT FA_TRN_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_fa_trn_type_2                     (p_row IN OUT FA_TRN_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_fixed_asset_2                      (p_row IN OUT FIXED_ASSET%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_fixed_asset_2                     (p_row IN OUT FIXED_ASSET%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_fixed_asset_categ_2                (p_row IN OUT FIXED_ASSET_CATEG%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_fixed_asset_categ_2               (p_row IN OUT FIXED_ASSET_CATEG%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_inventory_setup_2                  (p_row IN OUT INVENTORY_SETUP%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_inventory_setup_2                 (p_row IN OUT INVENTORY_SETUP%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_item_2                             (p_row IN OUT ITEM%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_item_2                            (p_row IN OUT ITEM%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_item_size_2                        (p_row IN OUT ITEM_SIZE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_item_size_2                       (p_row IN OUT ITEM_SIZE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_item_type_2                        (p_row IN OUT ITEM_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_item_type_2                       (p_row IN OUT ITEM_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_macrorouting_header_2              (p_row IN OUT MACROROUTING_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_macrorouting_header_2             (p_row IN OUT MACROROUTING_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_movement_type_2                    (p_row IN OUT MOVEMENT_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_movement_type_2                   (p_row IN OUT MOVEMENT_TYPE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_operation_2                        (p_row IN OUT OPERATION%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_operation_2                       (p_row IN OUT OPERATION%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_organization_2                     (p_row IN OUT ORGANIZATION%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_organization_2                    (p_row IN OUT ORGANIZATION%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_organization_loc_2                 (p_row IN OUT ORGANIZATION_LOC%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_organization_loc_2                (p_row IN OUT ORGANIZATION_LOC%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_package_header_2                   (p_row IN OUT PACKAGE_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_package_header_2                  (p_row IN OUT PACKAGE_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_patch_header_2                     (p_row IN OUT PATCH_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_patch_header_2                    (p_row IN OUT PATCH_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_po_ord_header_2                    (p_row IN OUT PO_ORD_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_po_ord_header_2                   (p_row IN OUT PO_ORD_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_primary_uom_2                      (p_row IN OUT PRIMARY_UOM%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_primary_uom_2                     (p_row IN OUT PRIMARY_UOM%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_sales_family_2                     (p_row IN OUT SALES_FAMILY%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_sales_family_2                    (p_row IN OUT SALES_FAMILY%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_setup_acrec_2                      (p_row IN OUT SETUP_ACREC%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_setup_acrec_2                     (p_row IN OUT SETUP_ACREC%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_setup_receipt_2                    (p_row IN OUT SETUP_RECEIPT%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_setup_receipt_2                   (p_row IN OUT SETUP_RECEIPT%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_setup_shipment_2                   (p_row IN OUT SETUP_SHIPMENT%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_setup_shipment_2                  (p_row IN OUT SETUP_SHIPMENT%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_shipment_header_2                  (p_row IN OUT SHIPMENT_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_shipment_header_2                 (p_row IN OUT SHIPMENT_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_shipment_package_2                 (p_row IN OUT SHIPMENT_PACKAGE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_shipment_package_2                (p_row IN OUT SHIPMENT_PACKAGE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_teh_variable_2                     (p_row IN OUT TEH_VARIABLE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_teh_variable_2                    (p_row IN OUT TEH_VARIABLE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_trn_plan_header_2                  (p_row IN OUT TRN_PLAN_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_trn_plan_header_2                 (p_row IN OUT TRN_PLAN_HEADER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_value_ad_tax_2                     (p_row IN OUT VALUE_AD_TAX%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_value_ad_tax_2                    (p_row IN OUT VALUE_AD_TAX%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_warehouse_2                        (p_row IN OUT WAREHOUSE%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_warehouse_2                       (p_row IN OUT WAREHOUSE%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_warehouse_categ_2                  (p_row IN OUT WAREHOUSE_CATEG%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_warehouse_categ_2                 (p_row IN OUT WAREHOUSE_CATEG%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_whs_trn_reason_2                   (p_row IN OUT WHS_TRN_REASON%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_whs_trn_reason_2                  (p_row IN OUT WHS_TRN_REASON%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_workcenter_2                       (p_row IN OUT WORKCENTER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_workcenter_2                      (p_row IN OUT WORKCENTER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_work_group_2                       (p_row IN OUT WORK_GROUP%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_work_group_2                      (p_row IN OUT WORK_GROUP%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_work_order_2                       (p_row IN OUT WORK_ORDER%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_work_order_2                      (p_row IN OUT WORK_ORDER%ROWTYPE, p_block INTEGER DEFAULT 0);
FUNCTION f_get_work_season_2                      (p_row IN OUT WORK_SEASON%ROWTYPE, p_block INTEGER DEFAULT 0) RETURN BOOLEAN;
PROCEDURE p_get_work_season_2                     (p_row IN OUT WORK_SEASON%ROWTYPE, p_block INTEGER DEFAULT 0);
END; 

/

/
