--------------------------------------------------------
--  DDL for Package PKG_MOD_COL
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PKG_MOD_COL" 
IS 
FUNCTION f_acrec_detail                           (p_row_old ACREC_DETAIL%ROWTYPE, p_row_new ACREC_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_acrec_header                           (p_row_old ACREC_HEADER%ROWTYPE, p_row_new ACREC_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_ac_account                             (p_row_old AC_ACCOUNT%ROWTYPE, p_row_new AC_ACCOUNT%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_ac_detail                              (p_row_old AC_DETAIL%ROWTYPE, p_row_new AC_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_ac_document                            (p_row_old AC_DOCUMENT%ROWTYPE, p_row_new AC_DOCUMENT%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_ac_header                              (p_row_old AC_HEADER%ROWTYPE, p_row_new AC_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_ac_period                              (p_row_old AC_PERIOD%ROWTYPE, p_row_new AC_PERIOD%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_app_doc_number                         (p_row_old APP_DOC_NUMBER%ROWTYPE, p_row_new APP_DOC_NUMBER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_app_user                               (p_row_old APP_USER%ROWTYPE, p_row_new APP_USER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_app_user_grant                         (p_row_old APP_USER_GRANT%ROWTYPE, p_row_new APP_USER_GRANT%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_bom_group                              (p_row_old BOM_GROUP%ROWTYPE, p_row_new BOM_GROUP%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_bom_std                                (p_row_old BOM_STD%ROWTYPE, p_row_new BOM_STD%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_bom_wo                                 (p_row_old BOM_WO%ROWTYPE, p_row_new BOM_WO%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_calendar                               (p_row_old CALENDAR%ROWTYPE, p_row_new CALENDAR%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_cat_custom                             (p_row_old CAT_CUSTOM%ROWTYPE, p_row_new CAT_CUSTOM%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_cat_mat_type                           (p_row_old CAT_MAT_TYPE%ROWTYPE, p_row_new CAT_MAT_TYPE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_colour                                 (p_row_old COLOUR%ROWTYPE, p_row_new COLOUR%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_costcenter                             (p_row_old COSTCENTER%ROWTYPE, p_row_new COSTCENTER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_cost_detail                            (p_row_old COST_DETAIL%ROWTYPE, p_row_new COST_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_cost_header                            (p_row_old COST_HEADER%ROWTYPE, p_row_new COST_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_cost_type                              (p_row_old COST_TYPE%ROWTYPE, p_row_new COST_TYPE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_country                                (p_row_old COUNTRY%ROWTYPE, p_row_new COUNTRY%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_currency                               (p_row_old CURRENCY%ROWTYPE, p_row_new CURRENCY%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_currency_rate                          (p_row_old CURRENCY_RATE%ROWTYPE, p_row_new CURRENCY_RATE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_custom                                 (p_row_old CUSTOM%ROWTYPE, p_row_new CUSTOM%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_delivery_condition                     (p_row_old DELIVERY_CONDITION%ROWTYPE, p_row_new DELIVERY_CONDITION%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_efficiency                             (p_row_old EFFICIENCY%ROWTYPE, p_row_new EFFICIENCY%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_fa_trn                                 (p_row_old FA_TRN%ROWTYPE, p_row_new FA_TRN%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_fa_trn_type                            (p_row_old FA_TRN_TYPE%ROWTYPE, p_row_new FA_TRN_TYPE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_fifo_exceding                          (p_row_old FIFO_EXCEDING%ROWTYPE, p_row_new FIFO_EXCEDING%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_fifo_material                          (p_row_old FIFO_MATERIAL%ROWTYPE, p_row_new FIFO_MATERIAL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_fixed_asset                            (p_row_old FIXED_ASSET%ROWTYPE, p_row_new FIXED_ASSET%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_fixed_asset_categ                      (p_row_old FIXED_ASSET_CATEG%ROWTYPE, p_row_new FIXED_ASSET_CATEG%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_group_routing                          (p_row_old GROUP_ROUTING%ROWTYPE, p_row_new GROUP_ROUTING%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_import_text_file                       (p_row_old IMPORT_TEXT_FILE%ROWTYPE, p_row_new IMPORT_TEXT_FILE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_inventory                              (p_row_old INVENTORY%ROWTYPE, p_row_new INVENTORY%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_inventory_detail                       (p_row_old INVENTORY_DETAIL%ROWTYPE, p_row_new INVENTORY_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_inventory_stoc                         (p_row_old INVENTORY_STOC%ROWTYPE, p_row_new INVENTORY_STOC%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_item                                   (p_row_old ITEM%ROWTYPE, p_row_new ITEM%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_item_cost                              (p_row_old ITEM_COST%ROWTYPE, p_row_new ITEM_COST%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_item_cycle_time                        (p_row_old ITEM_CYCLE_TIME%ROWTYPE, p_row_new ITEM_CYCLE_TIME%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_item_mapping                           (p_row_old ITEM_MAPPING%ROWTYPE, p_row_new ITEM_MAPPING%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_item_size                              (p_row_old ITEM_SIZE%ROWTYPE, p_row_new ITEM_SIZE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_item_type                              (p_row_old ITEM_TYPE%ROWTYPE, p_row_new ITEM_TYPE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_item_variable                          (p_row_old ITEM_VARIABLE%ROWTYPE, p_row_new ITEM_VARIABLE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_line                                   (p_row_old LINE%ROWTYPE, p_row_new LINE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_macrorouting_detail                    (p_row_old MACROROUTING_DETAIL%ROWTYPE, p_row_new MACROROUTING_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_macrorouting_header                    (p_row_old MACROROUTING_HEADER%ROWTYPE, p_row_new MACROROUTING_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_movement_type                          (p_row_old MOVEMENT_TYPE%ROWTYPE, p_row_new MOVEMENT_TYPE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_multi_table                            (p_row_old MULTI_TABLE%ROWTYPE, p_row_new MULTI_TABLE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_operation                              (p_row_old OPERATION%ROWTYPE, p_row_new OPERATION%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_organization                           (p_row_old ORGANIZATION%ROWTYPE, p_row_new ORGANIZATION%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_organization_loc                       (p_row_old ORGANIZATION_LOC%ROWTYPE, p_row_new ORGANIZATION_LOC%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_package_detail                         (p_row_old PACKAGE_DETAIL%ROWTYPE, p_row_new PACKAGE_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_package_header                         (p_row_old PACKAGE_HEADER%ROWTYPE, p_row_new PACKAGE_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_parameter                              (p_row_old PARAMETER%ROWTYPE, p_row_new PARAMETER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_parameter_attr                         (p_row_old PARAMETER_ATTR%ROWTYPE, p_row_new PARAMETER_ATTR%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_parameter_code                         (p_row_old PARAMETER_CODE%ROWTYPE, p_row_new PARAMETER_CODE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_price_list                             (p_row_old PRICE_LIST%ROWTYPE, p_row_new PRICE_LIST%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_price_list_sales                       (p_row_old PRICE_LIST_SALES%ROWTYPE, p_row_new PRICE_LIST_SALES%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_primary_uom                            (p_row_old PRIMARY_UOM%ROWTYPE, p_row_new PRIMARY_UOM%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_receipt_detail                         (p_row_old RECEIPT_DETAIL%ROWTYPE, p_row_new RECEIPT_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_receipt_header                         (p_row_old RECEIPT_HEADER%ROWTYPE, p_row_new RECEIPT_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_sales_family                           (p_row_old SALES_FAMILY%ROWTYPE, p_row_new SALES_FAMILY%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_sales_order                            (p_row_old SALES_ORDER%ROWTYPE, p_row_new SALES_ORDER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_scan_event                             (p_row_old SCAN_EVENT%ROWTYPE, p_row_new SCAN_EVENT%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_setup_acrec                            (p_row_old SETUP_ACREC%ROWTYPE, p_row_new SETUP_ACREC%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_setup_movement                         (p_row_old SETUP_MOVEMENT%ROWTYPE, p_row_new SETUP_MOVEMENT%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_setup_receipt                          (p_row_old SETUP_RECEIPT%ROWTYPE, p_row_new SETUP_RECEIPT%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_setup_shipment                         (p_row_old SETUP_SHIPMENT%ROWTYPE, p_row_new SETUP_SHIPMENT%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_shipment_detail                        (p_row_old SHIPMENT_DETAIL%ROWTYPE, p_row_new SHIPMENT_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_shipment_header                        (p_row_old SHIPMENT_HEADER%ROWTYPE, p_row_new SHIPMENT_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_shipment_order                         (p_row_old SHIPMENT_ORDER%ROWTYPE, p_row_new SHIPMENT_ORDER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_shipment_package                       (p_row_old SHIPMENT_PACKAGE%ROWTYPE, p_row_new SHIPMENT_PACKAGE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_so_detail                              (p_row_old SO_DETAIL%ROWTYPE, p_row_new SO_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_stg_bom_std                            (p_row_old STG_BOM_STD%ROWTYPE, p_row_new STG_BOM_STD%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_stg_file_manager                       (p_row_old STG_FILE_MANAGER%ROWTYPE, p_row_new STG_FILE_MANAGER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_stg_item                               (p_row_old STG_ITEM%ROWTYPE, p_row_new STG_ITEM%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_stg_ship_fifo                          (p_row_old STG_SHIP_FIFO%ROWTYPE, p_row_new STG_SHIP_FIFO%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_stg_work_order                         (p_row_old STG_WORK_ORDER%ROWTYPE, p_row_new STG_WORK_ORDER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_stg_wo_decl                            (p_row_old STG_WO_DECL%ROWTYPE, p_row_new STG_WO_DECL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_teh_variable                           (p_row_old TEH_VARIABLE%ROWTYPE, p_row_new TEH_VARIABLE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_trn_plan_detail                        (p_row_old TRN_PLAN_DETAIL%ROWTYPE, p_row_new TRN_PLAN_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_trn_plan_header                        (p_row_old TRN_PLAN_HEADER%ROWTYPE, p_row_new TRN_PLAN_HEADER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_value_ad_tax                           (p_row_old VALUE_AD_TAX%ROWTYPE, p_row_new VALUE_AD_TAX%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_virtual_table                          (p_row_old VIRTUAL_TABLE%ROWTYPE, p_row_new VIRTUAL_TABLE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_warehouse                              (p_row_old WAREHOUSE%ROWTYPE, p_row_new WAREHOUSE%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_warehouse_categ                        (p_row_old WAREHOUSE_CATEG%ROWTYPE, p_row_new WAREHOUSE_CATEG%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_web_grid_cm                            (p_row_old WEB_GRID_CM%ROWTYPE, p_row_new WEB_GRID_CM%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_whs_trn                                (p_row_old WHS_TRN%ROWTYPE, p_row_new WHS_TRN%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_whs_trn_detail                         (p_row_old WHS_TRN_DETAIL%ROWTYPE, p_row_new WHS_TRN_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_whs_trn_reason                         (p_row_old WHS_TRN_REASON%ROWTYPE, p_row_new WHS_TRN_REASON%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_workcenter                             (p_row_old WORKCENTER%ROWTYPE, p_row_new WORKCENTER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_workcenter_oper                        (p_row_old WORKCENTER_OPER%ROWTYPE, p_row_new WORKCENTER_OPER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_work_group                             (p_row_old WORK_GROUP%ROWTYPE, p_row_new WORK_GROUP%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_work_order                             (p_row_old WORK_ORDER%ROWTYPE, p_row_new WORK_ORDER%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_work_season                            (p_row_old WORK_SEASON%ROWTYPE, p_row_new WORK_SEASON%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_wo_detail                              (p_row_old WO_DETAIL%ROWTYPE, p_row_new WO_DETAIL%ROWTYPE) RETURN VARCHAR2;
FUNCTION f_wo_group                               (p_row_old WO_GROUP%ROWTYPE, p_row_new WO_GROUP%ROWTYPE) RETURN VARCHAR2;
END; 

/

/
