CREATE USER DA
  IDENTIFIED BY VALUES 'F78CB9AEB3C35DB9'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 22 Roles for DA 
  GRANT DELETE_CATALOG_ROLE TO DA WITH ADMIN OPTION;
  GRANT XDBADMIN TO DA WITH ADMIN OPTION;
  GRANT GATHER_SYSTEM_STATISTICS TO DA WITH ADMIN OPTION;
  GRANT AQ_ADMINISTRATOR_ROLE TO DA WITH ADMIN OPTION;
  GRANT SCHEDULER_ADMIN TO DA WITH ADMIN OPTION;
  GRANT OEM_MONITOR TO DA WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO DA WITH ADMIN OPTION;
  GRANT EXECUTE_CATALOG_ROLE TO DA WITH ADMIN OPTION;
  GRANT AQ_USER_ROLE TO DA WITH ADMIN OPTION;
  GRANT XDBWEBSERVICES TO DA WITH ADMIN OPTION;
  GRANT PLUSTRACE TO DA WITH ADMIN OPTION;
  GRANT RESOURCE TO DA WITH ADMIN OPTION;
  GRANT CONNECT TO DA WITH ADMIN OPTION;
  GRANT AUTHENTICATEDUSER TO DA WITH ADMIN OPTION;
  GRANT LOGSTDBY_ADMINISTRATOR TO DA WITH ADMIN OPTION;
  GRANT DBA TO DA WITH ADMIN OPTION;
  GRANT CTXAPP TO DA WITH ADMIN OPTION;
  GRANT SELECT_CATALOG_ROLE TO DA WITH ADMIN OPTION;
  GRANT RECOVERY_CATALOG_OWNER TO DA WITH ADMIN OPTION;
  GRANT OEM_ADVISOR TO DA WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO DA WITH ADMIN OPTION;
  GRANT HS_ADMIN_ROLE TO DA WITH ADMIN OPTION;
  ALTER USER DA DEFAULT ROLE ALL;
  -- 164 System Privileges for DA 
  GRANT CHANGE NOTIFICATION TO DA WITH ADMIN OPTION;
  GRANT MANAGE SCHEDULER TO DA WITH ADMIN OPTION;
  GRANT CREATE JOB TO DA WITH ADMIN OPTION;
  GRANT ADVISOR TO DA WITH ADMIN OPTION;
  GRANT EXPORT FULL DATABASE TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT FLASHBACK ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT DEBUG ANY PROCEDURE TO DA WITH ADMIN OPTION;
  GRANT DEBUG CONNECT SESSION TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'DA',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT CREATE TYPE TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY DIRECTORY TO DA WITH ADMIN OPTION;
  GRANT DROP PROFILE TO DA WITH ADMIN OPTION;
  GRANT CREATE PROFILE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY PROCEDURE TO DA WITH ADMIN OPTION;
  GRANT ALTER DATABASE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY ROLE TO DA WITH ADMIN OPTION;
  GRANT CREATE ROLE TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY SEQUENCE TO DA WITH ADMIN OPTION;
  GRANT LOCK ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT DROP ROLLBACK SEGMENT TO DA WITH ADMIN OPTION;
  GRANT ALTER TABLESPACE TO DA WITH ADMIN OPTION;
  GRANT ALTER SESSION TO DA WITH ADMIN OPTION;
  GRANT READ ANY FILE GROUP TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY JOB TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT SELECT ANY DICTIONARY TO DA WITH ADMIN OPTION;
  GRANT RESUMABLE TO DA WITH ADMIN OPTION;
  GRANT GLOBAL QUERY REWRITE TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY INDEXTYPE TO DA WITH ADMIN OPTION;
  GRANT EXECUTE ANY LIBRARY TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY LIBRARY TO DA WITH ADMIN OPTION;
  GRANT CREATE PUBLIC DATABASE LINK TO DA WITH ADMIN OPTION;
  GRANT CREATE SEQUENCE TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY VIEW TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY SYNONYM TO DA WITH ADMIN OPTION;
  GRANT DROP ANY INDEX TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY INDEX TO DA WITH ADMIN OPTION;
  GRANT DELETE ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT ADMINISTER SQL TUNING SET TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY SQL PROFILE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY SQL PROFILE TO DA WITH ADMIN OPTION;
  GRANT ON COMMIT REFRESH TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'DA',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT DROP ANY DIMENSION TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY INDEXTYPE TO DA WITH ADMIN OPTION;
  GRANT CREATE INDEXTYPE TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY OPERATOR TO DA WITH ADMIN OPTION;
  GRANT UNDER ANY TYPE TO DA WITH ADMIN OPTION;
  GRANT ALTER PROFILE TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY PROCEDURE TO DA WITH ADMIN OPTION;
  GRANT CREATE PROCEDURE TO DA WITH ADMIN OPTION;
  GRANT FORCE TRANSACTION TO DA WITH ADMIN OPTION;
  GRANT DROP PUBLIC DATABASE LINK TO DA WITH ADMIN OPTION;
  GRANT CREATE DATABASE LINK TO DA WITH ADMIN OPTION;
  GRANT DROP ANY SEQUENCE TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY INDEX TO DA WITH ADMIN OPTION;
  GRANT INSERT ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT ALTER ROLLBACK SEGMENT TO DA WITH ADMIN OPTION;
  GRANT CREATE SESSION TO DA WITH ADMIN OPTION;
  GRANT EXECUTE ANY CLASS TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT EXEMPT ACCESS POLICY TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY OUTLINE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY TYPE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY TRIGGER TO DA WITH ADMIN OPTION;
  GRANT AUDIT ANY TO DA WITH ADMIN OPTION;
  GRANT CREATE PUBLIC SYNONYM TO DA WITH ADMIN OPTION;
  GRANT BACKUP ANY TABLE TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT CREATE ANY CONTEXT TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY DIMENSION TO DA WITH ADMIN OPTION;
  GRANT CREATE DIMENSION TO DA WITH ADMIN OPTION;
  GRANT UNDER ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT CREATE MATERIALIZED VIEW TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY PROCEDURE TO DA WITH ADMIN OPTION;
  GRANT GRANT ANY ROLE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY VIEW TO DA WITH ADMIN OPTION;
  GRANT CREATE CLUSTER TO DA WITH ADMIN OPTION;
  GRANT COMMENT ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT CREATE USER TO DA WITH ADMIN OPTION;
  GRANT MANAGE TABLESPACE TO DA WITH ADMIN OPTION;
  GRANT AUDIT SYSTEM TO DA WITH ADMIN OPTION;
  GRANT MANAGE ANY FILE GROUP TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY SQL PROFILE TO DA WITH ADMIN OPTION;
  GRANT ADMINISTER ANY SQL TUNING SET TO DA WITH ADMIN OPTION;
  GRANT SELECT ANY TRANSACTION TO DA WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROGRAM TO DA WITH ADMIN OPTION;
  GRANT ANALYZE ANY DICTIONARY TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT IMPORT FULL DATABASE TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT GRANT ANY OBJECT PRIVILEGE TO DA WITH ADMIN OPTION;
  GRANT ADMINISTER DATABASE TRIGGER TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'DA', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => TRUE);
END;
/
  GRANT DROP ANY CONTEXT TO DA WITH ADMIN OPTION;
  GRANT CREATE OPERATOR TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY TYPE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY DIRECTORY TO DA WITH ADMIN OPTION;
  GRANT DROP ANY MATERIALIZED VIEW TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY MATERIALIZED VIEW TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY MATERIALIZED VIEW TO DA WITH ADMIN OPTION;
  GRANT GRANT ANY PRIVILEGE TO DA WITH ADMIN OPTION;
  GRANT ALTER RESOURCE COST TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY TRIGGER TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY TRIGGER TO DA WITH ADMIN OPTION;
  GRANT DROP PUBLIC SYNONYM TO DA WITH ADMIN OPTION;
  GRANT DROP ANY SYNONYM TO DA WITH ADMIN OPTION;
  GRANT CREATE SYNONYM TO DA WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT BECOME USER TO DA WITH ADMIN OPTION;
  GRANT DROP TABLESPACE TO DA WITH ADMIN OPTION;
  GRANT CREATE TABLESPACE TO DA WITH ADMIN OPTION;
  GRANT ALTER SYSTEM TO DA WITH ADMIN OPTION;
  GRANT CREATE EXTERNAL JOB TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT DROP ANY OUTLINE TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY OUTLINE TO DA WITH ADMIN OPTION;
  GRANT QUERY REWRITE TO DA WITH ADMIN OPTION;
  GRANT UNDER ANY VIEW TO DA WITH ADMIN OPTION;
  GRANT DROP ANY INDEXTYPE TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY OPERATOR TO DA WITH ADMIN OPTION;
  GRANT CREATE LIBRARY TO DA WITH ADMIN OPTION;
  GRANT EXECUTE ANY TYPE TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY TYPE TO DA WITH ADMIN OPTION;
  GRANT ANALYZE ANY TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY ROLE TO DA WITH ADMIN OPTION;
  GRANT CREATE VIEW TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY CLUSTER TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY CLUSTER TO DA WITH ADMIN OPTION;
  GRANT SELECT ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT CREATE ROLLBACK SEGMENT TO DA WITH ADMIN OPTION;
  GRANT ALTER USER TO DA WITH ADMIN OPTION;
  GRANT RESTRICTED SESSION TO DA WITH ADMIN OPTION;
  GRANT MANAGE FILE GROUP TO DA WITH ADMIN OPTION;
  GRANT EXEMPT IDENTITY POLICY TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DA',
  GRANT_OPTION => TRUE);
END;
/
  GRANT MERGE ANY VIEW TO DA WITH ADMIN OPTION;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'DA',
  ADMIN_OPTION => TRUE);
END;
/
  GRANT ALTER ANY DIMENSION TO DA WITH ADMIN OPTION;
  GRANT EXECUTE ANY INDEXTYPE TO DA WITH ADMIN OPTION;
  GRANT EXECUTE ANY OPERATOR TO DA WITH ADMIN OPTION;
  GRANT DROP ANY OPERATOR TO DA WITH ADMIN OPTION;
  GRANT DROP ANY LIBRARY TO DA WITH ADMIN OPTION;
  GRANT CREATE ANY LIBRARY TO DA WITH ADMIN OPTION;
  GRANT CREATE TRIGGER TO DA WITH ADMIN OPTION;
  GRANT EXECUTE ANY PROCEDURE TO DA WITH ADMIN OPTION;
  GRANT FORCE ANY TRANSACTION TO DA WITH ADMIN OPTION;
  GRANT SELECT ANY SEQUENCE TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY SEQUENCE TO DA WITH ADMIN OPTION;
  GRANT DROP ANY CLUSTER TO DA WITH ADMIN OPTION;
  GRANT ALTER ANY TABLE TO DA WITH ADMIN OPTION;
  GRANT CREATE TABLE TO DA WITH ADMIN OPTION;
  GRANT DROP USER TO DA WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO DA WITH ADMIN OPTION;
  -- 2 Object Privileges for DA 
    GRANT EXECUTE ON  SYS.DBMS_DATAPUMP TO DA;
    GRANT EXECUTE ON  SYS.UTL_FILE TO DA WITH GRANT OPTION;


